# Generated by Django 3.0.5 on 2021-06-19 13:21

from django.db import migrations, models
import djongo.models.fields
import pizza_API.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('Toppings', djongo.models.fields.ArrayField(model_container=pizza_API.models.Topping_item)),
            ],
        ),
        migrations.CreateModel(
            name='Size_item',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
